global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "kafka_jmx"
    static_configs:
      - targets: ["kafka:9999"]

  - job_name: "kafka_exporter"
    static_configs:
      - targets: ["kafka_exporter:9308"]
